### ISSUE TITLE
[frontend] create repo and setup

### ISSUE THREAD

**Issue by xoxwgys56** [xoxwgys56/j2kb-news-reply-sentiment-analysis#1]
## frontend 

저장소 생성 및 초기셋업 해주세요.

**Comment by xoxwgys56** [comment]
서브모듈로 프론트엔드 저장소를 추가해주세요. (그게 보기 편할거 같아서요.)

아시겠지만, 아래 방법으로 추가하시면 됩니다.
```shell
git submodule add <repo-url>
```

**Comment by waltererz** [comment]
프론트엔드 저장소 추가했습니다.
프론트엔드 테스트 URL은 [http://newsreply.erzsphilos.com](http://newsreply.erzsphilos.com) 입니다.

**Comment by xoxwgys56** [comment]
@waltererz 

확인 감사드립니다. 혹시 도메인은 어떻게 설정하셨는지 알려주실 수 있을까요?  
프론트 배포는 어떻게 하시는지 궁금하네요.

**Comment by xoxwgys56** [comment]
@waltererz 

추가적으로 완료된 card를 `project` 탭에서 확인하실 수 있습니다. 완료되었으므로, done 상태로 이동시키겠습니다.

**Comment by waltererz** [comment]
@xoxwgys56 

호스팅 업체에서 도메인 구입 후 DNS 설정에서 가상서버 IP주소를 도메인에 연결시켰습니다.
우분투에 아파치 서버를 설치했고, 아파치를 설치하면 인바운드 포트 설정 등등을 알아서 해주기 때문에 저는 도메인에 IP주소를 연결하기만 했습니다. (가상머신 마이크로소프트 애저에서 정적 IP 할당 받음)

프론트 배포는 도메인을 구입한 후 연결하면 되는 것으로 알고 있습니다. 저는 카페24([cafe24.com](https://hosting.cafe24.com/))를 이용했습니다.

![화면 캡처 2021-07-19 094545](https://user-images.githubusercontent.com/7940031/126087799-bf0efcc1-8ca7-4183-9eb7-e7fd6104de04.png)

**Comment by xoxwgys56** [comment]
@waltererz 

답변 감사드립니다. 그렇다면 빌드는 로컬에서 진행하고 사용하시는 호스팅 서비스로 배포하시는건가요?  
아니면 별도의 CI/CD를 이용하시는지요.

**Comment by waltererz** [comment]
@xoxwgys56 

맥북에서 SSH를 통해 가상머신에 연결해 개발을 진행하고 있습니다. 저한테는 가상머신이 로컬이라고 할 수 있는데, 도메인도 연결되어 있어 인터넷에서도 접속은 가능합니다. 리눅스 노트북을 구입하는 것보다 가상머신이 훨씬 저렴하기 때문에 이렇게 하고 있습니다.

그런데 개발용이기 때문에 여러 명이 접속할 수 있을 정도로 RAM이 크지는 않아서, 나중에 배포할 때는 더 성능이 좋은 가상머신을 구매해야 합니다. 이전에 AWS를 사용하신다고 들었습니다. 프론트엔드는 Github에서 소스코드를 다운로드하면 곧바로 배포할 수 있는 수준입니다.

**Comment by xoxwgys56** [comment]
@waltererz 

이해했습니다. 현명한 방법을 사용하고 계시는군요.  
네 말씀하신대로 배포를 할 경우 가용폭이 더 넓은 인스턴스가 필요하겠네요.  

아파치에서 동시에 많은 사용자가 접근할 경우 어떻게 처리하는지 모르겠네요.  
아파치 내에서 관리가 어렵다면, 별도의 프론트엔드 서버 애플리케이션이 필요할 수도 있겠네요.
