### ISSUE TITLE
프론트엔드 기술 정리 문서

### ISSUE THREAD

**Issue by xoxwgys56** [xoxwgys56/j2kb-news-reply-sentiment-analysis#13]
프론트엔드에서 사용하는 배포 및 사용 기술에 대해 정리된 문서 작성 부탁드립니다.

제가 이해하기론 호스팅은 `cafe24` 프론트와 백은 `reactJS`, `Lalavel`을 사용하시는 것으로 알고 있습니다.  
하지만 이 기술들에 대해 `README` 문서에 언급이 되어 있지 않습니다. 또한 각각의 기술들이 어떤 목적으로 사용되는지 (위에서 언급한 것처럼 front: reactJS)에 대해 간략히 언급된 문서를 작성 부탁드립니다.  

이 프로젝트의 `notion`이나 생성하신 저장소의 `README`에 작성해주셔도 좋을 것 같습니다.

**Comment by waltererz** [comment]
@xoxwgys56 Github README 파일에 관련 내용을 작성했습니다. 추가적으로 필요한 내용 있는지 확인 부탁드리겠습니다!

https://github.com/waltererz/news-reply-sentiment-frontend

**Comment by xoxwgys56** [comment]
@waltererz 

확인했습니다. 제가 예상한 것보다 더 자세하게 적어주셨네요. 관련된 내용은 해당 이슈에 적어서 이 이슈는 닫도록 하겠습니다!
