### ISSUE TITLE
회원가입 및 로그인 폼 작성

### ISSUE THREAD

**Issue by waltererz** [xoxwgys56/j2kb-news-reply-sentiment-analysis#7]
회원가입 및 로그인 양식 작성

1. 카카오톡, 네이버, 구글 등 기타 SNS 연동 로그인을 위한 각종 버튼 포함

2. SNS 연동 로그인을 하는 경우 HTTPS 접속이 필요할 듯 (아마 SNS에서 HTTPS 접속을 강제할 것인데, 그럴 경우에는 도메인 인증서를 구매해야 합니다. 연 3만원 정도.)

3. 아이디는 이메일주소로... SNS 가 아닌 기본 회원가입 기능을 사용하는 회원의 패스워드는 SHA-3 해싱으로 데이터베이스에 저장해야 안전할 것 같습니다.

4. DBMS는 어떤 걸 활용하시는지요? (MySQL, MongoDB 등등..)

**Comment by xoxwgys56** [comment]
@waltererz 

- 저는 도메인 인증서 구매해본 경험이 없어서 어떻게 진행되는지 잘모르겠으나, 비용을 지불하고 사용하는 것도 괜찮다고 생각합니다.
   - 알아보니 aws에서 SSL/TLS 인증서를 제공하는 리소스가 있네요. [AWS Certificate Manager](https://docs.aws.amazon.com/ko_kr/acm/latest/userguide/acm-overview.html)
   - aws 리소스를 사용하면 비용은 무료라고 하네요.
- 기본 회원가입 기능을 제공하지 않는 것은 좋지않겠죠..? 암호화해서 저장해야겠네요. 말씀해주신 SHA-3 외에도 다른 방법이 있는지 알아보겠습니다.
- DBMS는 아직 결정하지 않았습니다. RDS를 사용하려고 합니다. (MySQL, Postgresql 중 하나로 생각하고 있습니다.)

**Comment by waltererz** [comment]
회원가입 및 로그인 폼 작성 완료

회원로그인: http://newsreply.erzsphilos.com/user/signin
회원가입: http://newsreply.erzsphilos.com/user/signup
